# Generated by Django 5.1.3 on 2024-11-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=150, verbose_name='نام کاربری')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='آواتار')),
                ('is_active', models.BooleanField(default=True, verbose_name='کاربر کارمند')),
                ('is_admin', models.BooleanField(default=False, verbose_name='کاربر ادمین')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
