# Generated by Django 5.1.3 on 2024-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(default=1, max_length=254, verbose_name=' ایمیل نویسنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=1, max_length=100, verbose_name='نویسنده'),
            preserve_default=False,
        ),
    ]
