# Generated by Django 5.1.3 on 2024-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_comment_user_comment_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default=1, max_length=444),
            preserve_default=False,
        ),
    ]
