# Generated by Django 5.1.3 on 2024-11-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
